version: "3.7"
services:
    gateway:
        build:
            context: gateway/docker
            dockerfile: development/nginx/Dockerfile
        ports:
            - "8080:8080"
            - "8081:8081"
        depends_on:
            - frontend
            - api

    frontend:
        build:
            context: frontend/docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - ./frontend:/app

    api:
        build:
            context: api/docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - ./api:/app
        depends_on:
            - api-php-fpm

    api-php-fpm:
        build:
            context: api/docker
            dockerfile: development/php-fpm/Dockerfile
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            DB_HOST: api-postgres
            DB_USER: dev
            DB_PASSWORD: secret
            DB_NAME: app
        volumes:
            - ./api:/app

    api-php-cli:
        build:
            context: api/docker
            dockerfile: development/php-cli/Dockerfile
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            DB_HOST: api-postgres
            DB_USER: dev
            DB_PASSWORD: secret
            DB_NAME: app
        volumes:
            - ./api:/app

    api-postgres:
        image: postgres:13.3-alpine
        environment:
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        volumes:
            - api-postgres:/var/lib/postgresql/data
        ports:
            - "54321:5432"

volumes:
    api-postgres: